# -*- coding: utf-8 -*-
"""ProyectoBlack.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19MQ-E9ABNKFtSv00PnncnkOakVO245vH
"""

import random # Se requiere para revolver la baraja y que las cartas sean aleatorias

def crear_baraja():
    palos = ("\u2660", "\u2665", "\u2666", "\u2663") # Picas, Corazones, Diamantes, Tréboles en ascII
    valores_cartas = [
        ("2", 2), ("3", 3), ("4", 4), ("5", 5), ("6", 6), ("7", 7),
        ("8", 8), ("9", 9), ("10", 10), ("J", 10), ("Q", 10), ("K", 10), ("A", 11)
    ]

    baraja = []
    for palo in palos:
        for carta, valor in valores_cartas:
            baraja.append((carta, palo, valor))

    random.shuffle(baraja) # BARAJADA PARA REPARTIR
    return baraja

def calcular_puntos(mano):
    total = 0
    for carta in mano:
        total += carta[2]
    # Recordar que el AS puede valer 1 o 11
    if total > 21:
        for carta in mano:
            if carta[0] == "A" and total > 21:
                total -= 10
    return total

def mostrar_mano(nombre, mano, ocultar_primera=False):
    print(f"\nMano de {nombre}:")
    if ocultar_primera:
        print("[Carta Oculta]")
        for carta in mano[1:]:
            print(f"{carta[0]}{carta[1]}")
    else:
        for carta in mano:
            print(f"{carta[0]}{carta[1]}")
        print(f"Puntos totales: {calcular_puntos(mano)}")

def turno_jugador(baraja, mano_jugador):
    mostrar_mano("Jugador", mano_jugador)
    puntos = calcular_puntos(mano_jugador)

    if puntos > 21:
        print("¡Tu suma es mayor de 21! Has perdido.")
        return puntos

    if puntos == 21:
        print("¡Felicitaciones, Tienes 21!")
        return puntos

    opcion = input("\n¿Si Quieres Pedir carta oprime (1) ó (2) Plantarte? : ")

    if opcion == "1":
        carta_nueva = baraja.pop()
        mano_jugador.append(carta_nueva)
        print(f"Robaste: {carta_nueva[0]}{carta_nueva[1]}")
        return turno_jugador(baraja, mano_jugador)
    else:
        print("Te has plantado.")
        return puntos

def jugar_ronda(fichas):
    print("\n" + "="*30)
    print(f"Tiene {fichas} fichas.")

    apuesta = int(input("¿Cuánto quiere apostar?: "))
    while apuesta > fichas or apuesta <= 0:
        apuesta = int(input("Apuesta inválida. Introduce una cantidad correcta: "))

    baraja = crear_baraja()
    mano_jugador = [baraja.pop(), baraja.pop()]
    mano_casa = [baraja.pop(), baraja.pop()]
    mostrar_mano("Casa", mano_casa, ocultar_primera=True)
    puntos_jugador = turno_jugador(baraja, mano_jugador)

    puntos_casa = calcular_puntos(mano_casa)
    if puntos_jugador <= 21:
        mostrar_mano("Casa", mano_casa)
        while puntos_casa < 17:
            carta_nueva = baraja.pop()
            mano_casa.append(carta_nueva)
            print(f"La casa toma: {carta_nueva[0]}{carta_nueva[1]}")
            puntos_casa = calcular_puntos(mano_casa)
            mostrar_mano("Casa", mano_casa)

    print("AVANCE")
    if puntos_jugador > 21:
        fichas -= apuesta
    elif puntos_casa > 21:
        print("¡La casa se pasó!, ¡Ganaste!")
        fichas += apuesta
    elif puntos_jugador > puntos_casa:
        print("¡Ganaste la mano!")
        fichas += apuesta
    elif puntos_jugador < puntos_casa:
        print("La casa gana.")
        fichas -= apuesta
    else:
        print("Empate.")

    return fichas

def juego_blackjack():
    print("¡Bienvenido al juego de Blackjack para Principiantes!")
    fichas_totales = 100

    while fichas_totales > 0:
        fichas_totales = jugar_ronda(fichas_totales)

        if fichas_totales <= 0:
            print("\nTe has quedado sin fichas. ¡Fin del juego!")
            break

        continuar = input("\n¿Deseas jugar otra ronda? (s/n): ").lower()
        if continuar != 's':
            print(f"\nTe retiras con {fichas_totales} fichas. ¡Gracias por jugar!")
            break

# Para ejecutar el juego:
juego_blackjack()